version: '3'
services:
  web:
    container_name: web_server
    build: .
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
    volumes:
      - "./test-app:/var/www/html"
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
      - "433:433"
  mysql:
    image: mysql:5.7
    container_name: mysql_server
    volumes:
        - ./docker/runtime/mysql/lib:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: testdrive
        MYSQL_PASSWORD: testdrive
        MYSQL_DATABASE: testdrive
    ports:
      - "3306:3306"
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_server
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"